### ISSUE TITLE
`npm test` fails with "Error: Cannot find module './webpack.config'"

### ISSUE THREAD

**Issue by carlgieringer** [valor-software/ng2-dragula#121]
Hi,

Should I be providing my own webpack.config for running the tests?  When I perform a clean checkout and run `npm test`, I am getting the following:

```
tech@dyson ~/code/ng2-dragula (master●)$ npm test

> ng2-dragula@1.1.2 test /Users/tech/code/ng2-dragula
> karma start

08 03 2016 09:07:45.611:ERROR [config]: Invalid config file!
  Error: Cannot find module './webpack.config'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/tech/code/ng2-dragula/karma.conf.js:2:21)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.parseConfig (/Users/tech/code/ng2-dragula/node_modules/karma/lib/config.js:277:22)
    at new Server (/Users/tech/code/ng2-dragula/node_modules/karma/lib/server.js:56:20)
    at Object.exports.run (/Users/tech/code/ng2-dragula/node_modules/karma/lib/cli.js:235:7)
    at Object.<anonymous> (/Users/tech/code/ng2-dragula/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:413:34)
npm ERR! Test failed.  See above for more details.
```

Thank you!

**Comment by NathanWalker** [comment]
@carlgieringer Thanks for head up! Indeed the `webpack.config.js` was missing! Just fixed it now. Pull the latest :+1:  

Also, there actually aren't any tests at the moment. I am seeking some help for those due to time constraints.

**Comment by carlgieringer** [comment]
Got it now.  Thanks!
