### ISSUE TITLE
usage with angular2-seed (again)

### ISSUE THREAD

**Issue by thomasbee** [valor-software/ng2-dragula#186]
I am again trying to use ng2-dragula 1.1.5 and dragula 3.6.8 with mgechev's angular 2 seed. The mappings are working fine now, and I have also added the following to project.config.ts

```
   let additional_deps: InjectableDependency[] = [
      {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      {src: 'toastr/package/build/toastr.min.js', inject: 'libs'},
      {src: 'dragula/dist/dragula.min.js', inject: 'libs'},
      {src: 'semantic-ui-tab/tab.min.js', inject: 'libs'}
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
    ];
```
import is as follows:

```
import {Dragula, DragulaService} from 'ng2-dragula/ng2-dragula';
```

I do not get compile errors, all fine, but during bootstrapping the browser throws an error in ticky.js, i.e. 
```
Error: ReferenceError: undef is not defined
```

Full trace in Chrome is as follows
```
localhost/:94 Error: ReferenceError: undef is not defined
	    at Object.eval (http://localhost:5555/node_modules/ticky/ticky.js:4:44)
	    at eval (http://localhost:5555/node_modules/ticky/ticky.js:12:4)
	    at eval (http://localhost:5555/node_modules/ticky/ticky.js:13:3)
	    at Object.eval (http://localhost:5555/node_modules/contra/debounce.js:3:13)
	Evaluating http://localhost:5555/node_modules/ticky/ticky.js
	Evaluating http://localhost:5555/node_modules/contra/debounce.js
	Evaluating http://localhost:5555/node_modules/contra/emitter.js
	Evaluating http://localhost:5555/node_modules/dragula/dragula.js
	Evaluating http://localhost:5555/node_modules/ng2-dragula/src/app/providers/dragula.provider.js
	Evaluating http://localhost:5555/node_modules/ng2-dragula/src/app/directives/dragula.directive.js
	Evaluating http://localhost:5555/node_modules/ng2-dragula/ng2-dragula.js
	Evaluating http://localhost:5555/home/components/run.component.js
	Evaluating http://localhost:5555/home/components/run-tree.component.js
	Evaluating http://localhost:5555/app/components/app.component.js
	Evaluating http://localhost:5555/main.js
	Error loading http://localhost:5555/main.js "Report this error at https://github.com/mgechev/angular2-seed/issues"
```
The relevant code snippet in ticky.js is
```
var si = typeof setImmediate === 'function', tick;
if (si) {
  tick = function (fn) { setImmediate(fn); };
} else if (typeof process !== undef && process.nextTick) {
  tick = process.nextTick;
} else {
  tick = function (fn) { setTimeout(fn, 0); };
}

module.exports = tick;
```

Any thoughts?

**Comment by thomasbee** [comment]
To reproduce

```
git clone --depth 1 https://github.com/mgechev/angular2-seed.git
cd angular2-seed
npm install
npm i dragula -save
npm i ng2-dragula -save
```
then in file src/app/app.component.ts import and use, for example
```
import {Component} from 'angular2/core';
import {ROUTER_DIRECTIVES, RouteConfig} from 'angular2/router';
import {NavbarComponent} from './navbar.component';
import {ToolbarComponent} from './toolbar.component';
import {HomeComponent} from '../../home/components/home.component';
import {AboutComponent} from '../../about/components/about.component';
import {NameListService} from '../../shared/services/name-list.service';
import {Dragula, DragulaService} from 'ng2-dragula/ng2-dragula';

@Component({
  selector: 'sd-app',
  viewProviders: [NameListService, DragulaService],
  moduleId: module.id,
  templateUrl: './app.component.html',
  directives: [ROUTER_DIRECTIVES, NavbarComponent, ToolbarComponent, Dragula]
})
@RouteConfig([
  { path: '/',      name: 'Home',  component: HomeComponent  },
  { path: '/about', name: 'About', component: AboutComponent }
])
export class AppComponent {}
```
run with
```
npm start
```
This will produce the reported problem in the browser.

**Comment by NathanWalker** [comment]
Did you follow instructions here regarding modifying system config?
https://github.com/valor-software/ng2-dragula/wiki#angular2-seed

**Comment by thomasbee** [comment]
Hi Nathan,

the instructions seem a bit outdated because the seed has changed, what I also tried is to add to tools/config/project.config.ts the following

```
  let additional_deps: InjectableDependency[] = [
      {src: 'dragula/dist/dragula.js', inject: 'libs'}
    ];
```
The behaviour is unchanged. Note that the mapping for ng2-dragula is now covered by the * rule in
seed.config.ts, i.e.

```
 protected SYSTEM_CONFIG_DEV = {
    defaultJSExtensions: true,
    packageConfigPaths: [`${this.APP_BASE}node_modules/*/package.json`],
    paths: {
      [this.BOOTSTRAP_MODULE]: `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`,
      'angular2/*': `${this.APP_BASE}angular2/*`,
      'rxjs/*': `${this.APP_BASE}rxjs/*`,
      '*': `${this.APP_BASE}node_modules/*`
    },
    packages: {
      angular2: { defaultExtension: false },
      rxjs: { defaultExtension: false }
    }
  };
```

**Comment by NathanWalker** [comment]
The directory structure changed but the instructions are still the same. Mapping has never been needed by `ng2-dragula` so the `*` is irrelevant there.

I'll update instructions here in moment to reflect new directory, but this is still what you need in `tools/config/seed.config.ts`:
```
const SYSTEM_CONFIG_DEV = {
  defaultJSExtensions: true,
  paths: {
    [this.BOOTSTRAP_MODULE]: `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`,
    'angular2/*': `${this.APP_BASE}angular2/*`,
    'rxjs/*': `${this.APP_BASE}rxjs/*`,
    'dragula': `${this.APP_BASE}node_modules/dragula/dist/dragula`,  // or .min, whichever
    '*': `${this.APP_BASE}node_modules/*`
  },
  packages: {
    angular2: { defaultExtension: false },
    rxjs: { defaultExtension: false }
  }
};

SYSTEM_BUILDER_CONFIG = {
    defaultJSExtensions: true,
    paths: {
      [`${this.TMP_DIR}/*`]: `${this.TMP_DIR}/*`,
      'dragula': `node_modules/dragula/dist/dragula.min.js`,
      '*': 'node_modules/*'
    }
  };
```

**Comment by NathanWalker** [comment]
btw, `ng2-dragula` and `dragula` are 2 different things. From your comment above, sounds like you may have been confused there.

`dragula` is the global that needs the system config help, not `ng2-dragula`. :+1:

**Comment by NathanWalker** [comment]
You don't need to change anything with `let additional_deps: InjectableDependency` as you mention in the original post here. This is mentioned in seed wiki. In most cases, just modifying system config as my comment and the wiki here mentions is all thats needed.

**Comment by thomasbee** [comment]
@NathanWalker ok, sorry my bad, I followed your instructions by adding to `tools/config/seed.config.ts` and it works again. However, although this is off-topic, I am failing to understand in which cases one would then add to `tools/config/project.config.ts`. The seed itself comes with a commented out example of adding a jquery dependency in the latter file. I would not say that this is particularly clearly explain in the seed.

Anyway, thanks a lot for the immediate help and my apologies. I will close the ticket.
