### ISSUE TITLE
Getting error second time getting to page with ng2-dragula

### ISSUE THREAD

**Issue by vitaly87** [valor-software/ng2-dragula#495]
I am trying to prevent user to move first element of dragulaService, the code work first time ok without the errors. the second time that I came back to this page I see an errors,

the code that doing the error:

```
constructor(public service:SmartTablesService, private dragulaService:DragulaService) {
    dragulaService.setOptions('nested-bag', {
      revertOnSpill: true,
      moves: function (el:any, container:any, handle:any):any {
        if (handle.className === 'sorting-table-title') {
          return false;
        } else {
          return true;
        }

      }
    });
```
the error is:

```
error_handler.js:48 EXCEPTION: Uncaught (in promise): Error: Error in ./SortTableComponent class SortTableComponent_Host - inline template:0:0 caused by: Bag named: "nested-bag" already exists.
Error: Bag named: "nested-bag" already exists.
    at DragulaService.add (http://platform.local:8080/3.chunk.js:1070:19)
    at DragulaService.setOptions (http://platform.local:8080/3.chunk.js:1099:24)
    at new SortTableComponent (http://platform.local:8080/3.chunk.js:1311:24)
```

**Comment by vitaly87** [comment]
ngOnDestroy() {
    this.dragulaService.destroy('nested-bag');
  }
