### ISSUE TITLE
error

### ISSUE THREAD

**Issue by balajibk5** [valor-software/ng2-dragula#499]
Uncaught TypeError: ctorParameters.map is not a function
    at ReflectionCapabilities.parameters (http://localhost:4200/main.bundle.js:51590:47)
    at Reflector.parameters (http://localhost:4200/main.bundle.js:51802:48)
    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:4200/main.bundle.js:29171:54)
    at CompileMetadataResolver.getTypeMetadata (http://localhost:4200/main.bundle.js:29136:26)
    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:4200/main.bundle.js:28911:28)
    at http://localhost:4200/main.bundle.js:28980:49
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/main.bundle.js:28973:44)
    at http://localhost:4200/main.bundle.js:28961:50
    at Array.forEach (native)
client?93b6:38 [WDS] Errors while compiling.

**Comment by ls-spavel** [comment]
I experience the same issue as soon as I add the import to the AppModule

**Comment by stevenknox** [comment]
Getting the same issue

**Comment by cormacrelf** [comment]
Should be ok in v2 with Angular Package Format.
